// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wcibmdmobempwfhxjjjq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndjaWJtZG1vYmVtcHdmaHhqampxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2OTA2MzQsImV4cCI6MjA3MzI2NjYzNH0.vW0rdeO6tySqj6r2_gF8xLMC0V9LQ9CcZLSIgADCZ-A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});